name: .NET Build and Test

on:
  push:
    branches:
      - 'test/PabloCaldas'   # Replace with your actual branch name
  pull_request:
    branches:
      - 'test/PabloCaldas'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x' # Use the version required by your project

    - name: Install dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --configuration Debug --verbosity normal
